Add graph canonize algorithm
votca/tools pull request #219
Opened 2020-03-11 02:47 UTC by JoshuaSBrown

This allows one to provide two graphs that are the same an check to see that the nodes/vertices in the graph are arranged in the same order. The idea behind this is to simplify the user experience. If you provide two molecules of the same type to votca, but the atoms are arranged differently in each molecule it is impossible to use the mapping functionality. This pull request helps to solve the problem by canonizing the order.

2020-03-11 14:04 UTC, JensWehner approved these changes
code wise it looks good to me. I am not sure what it is needed for, but I trust you.

2020-03-11 15:14 UTC, junghans commented
Some of the tests fail with clang-10, e.g.:
```
 22/277 Test  #22: unit_test_graphalgorithm ...........................***Failed    0.03 sec
 Running 6 test cases...
 is single network 1
 EDGE CHECK **************************************
 struct ID A Dist0labelaDist1labelaDist1labelaDist1labelbDist2labelb
 struct ID B Dist0labelaDist1labelaDist1labelaDist1labelbDist2labelb
 Print Sequence
 A     B    Cannonized A     Cannonzied B     Degree A   Degree B
 ================================================================
 2     3          a               a              3          3
 5     1          b               b              2          2
 3     2          a               a              2          2
 1     4          a               a              1          1
 4     5          b               b              2          2
 /builds/votca/tools/votca/tools/src/tests/test_graphalgorithm.cc(907): error: in "graphalgorithm_test/find_canonized_sequence_test": check sequence_A.at(2) == 1 has failed [3 != 1]
 /builds/votca/tools/votca/tools/src/tests/test_graphalgorithm.cc(908): error: in "graphalgorithm_test/find_canonized_sequence_test": check sequence_A.at(3) == 3 has failed [1 != 3]
 /builds/votca/tools/votca/tools/src/tests/test_graphalgorithm.cc(913): error: in "graphalgorithm_test/find_canonized_sequence_test": check sequence_B.at(2) == 4 has failed [2 != 4]
 /builds/votca/tools/votca/tools/src/tests/test_graphalgorithm.cc(914): error: in "graphalgorithm_test/find_canonized_sequence_test": check sequence_B.at(3) == 2 has failed [4 != 2]
 /builds/votca/tools/votca/tools/src/tests/test_graphalgorithm.cc(919): error: in "graphalgorithm_test/find_canonized_sequence_test": check gA.getDegree(sequence_A.at(2)) == 1 has failed [2 != 1]
 /builds/votca/tools/votca/tools/src/tests/test_graphalgorithm.cc(920): error: in "graphalgorithm_test/find_canonized_sequence_test": check gA.getDegree(sequence_A.at(3)) == 2 has failed [1 != 2]
 /builds/votca/tools/votca/tools/src/tests/test_graphalgorithm.cc(925): error: in "graphalgorithm_test/find_canonized_sequence_test": check gB.getDegree(sequence_B.at(2)) == 1 has failed [2 != 1]
 /builds/votca/tools/votca/tools/src/tests/test_graphalgorithm.cc(926): error: in "graphalgorithm_test/find_canonized_sequence_test": check gB.getDegree(sequence_B.at(3)) == 2 has failed [1 != 2]
 *** 8 failures are detected in the test module "graphalgorithm_test"
```

2020-04-10 21:16 UTC, junghans commented
We will have to merge #222 first.

2020-04-11 10:48 UTC, JensWehner requested changes
I feel the API is not optimal yet, as is some of the naming. I like the extensive testing. How to give values to Nodes we should discuss a bit further.

2020-04-11 10:48 UTC, JensWehner commented on include/votca/tools/graphalgorithm.h
> +std::string findCanonizedSequence(Graph& graph, std::vector<Index>& sequence);
why are the graph and the sequence not `const`? What are the side effects, is there maybe a better name or multiple functions?

2020-04-11 10:48 UTC, JensWehner commented on include/votca/tools/graphdistvisitor.h
>    void exploreNode(std::pair<Index, GraphNode>& p_gn, Graph& g,
exploreNode is not a very descriptive name, considering nearly all arguments are not const

2020-04-11 10:48 UTC, JensWehner commented on include/votca/tools/graphalgorithm.h
> +std::string findCanonizedSequence(Graph& graph, std::vector<Index>& sequence);
if sequence is a return value, just return a std::pair<std::string,std::vector>?

2020-04-11 10:48 UTC, JensWehner commented on include/votca/tools/graphmemoryvisitor.h
> +  std::vector<Index> getMemory() const noexcept { return memory_; }
you want to return a copy and not a const reference?

2020-04-11 10:48 UTC, JensWehner commented on include/votca/tools/graphmemoryvisitor.h
> +  void exploreNode(std::pair<Index, GraphNode>& p_gn, Graph& g,
I am not super happy with the name ``exploreNode` because it is pretty unspecific.

2020-04-11 10:48 UTC, JensWehner commented on include/votca/tools/graphnode.h
> +
concerning how to carry values. I think if you want to make it general, template the whole thing on the value type. Then people can create their own structs etc...

2020-04-11 10:48 UTC, JensWehner commented on include/votca/tools/graphvisitor.h
> +                           Graph& graph, const Edge& edge = DUMMY_EDGE);
what does the dummyedge do?

2020-04-11 10:48 UTC, JensWehner commented on include/votca/tools/graphvisitor.h
> +                           Graph& graph, const Edge& edge = DUMMY_EDGE);
instead of a default arguement, having two functions with different parameters is better, because it is easier to extend.

2020-04-11 10:48 UTC, JensWehner commented on src/libtools/graphalgorithm.cc
> +  // Get the vertices with this degree
I think this function would profit from more functions inside

2020-04-11 10:48 UTC, JensWehner commented on src/libtools/graphmemoryvisitor.cc
> +using namespace std;
still not a fan of this

2020-04-11 10:48 UTC, JensWehner commented on src/libtools/graphmemoryvisitor.cc
> +      p_gn.second.addInt("Dist", gn_prev.getInt("Dist") + 1);
you use a value property for the properties of the  graph that is dangerous? What happens if I have a value Dist on my object?

2020-04-15 15:50 UTC, junghans requested changes
clang-10 failures:
```
 The following tests FAILED:
 	 24 - unit_test_graphalgorithm (Failed)
 	 25 - memory_test_graphalgorithm (Failed)
 Errors while running CTest
```

2020-04-15 16:52 UTC, JoshuaSBrown commented
I'm well aware this fails, outputting the ids of a molecule in a unique sequence, that is specific to the molecule is not a trivial thing to do. With the current implementation it should fail which speaks to the importance of our testing framework. I have been working on fixing this but like I said this is not a straightforward problem to solve.

2020-04-15 17:00 UTC, JoshuaSBrown commented
actually I'm not confused as to why the ci is passing.

2020-04-15 17:28 UTC, junghans commented
> actually I'm now confused as to why the ci is passing.

Clang-10 is part of Rawhide and Rawhide build are allowed to fail.

2020-05-04 13:51 UTC, JoshuaSBrown commented
> I feel the API is not optimal yet, as is some of the naming. I like the extensive testing. How to give values to Nodes we should discuss a bit further.

You are completely right, I need help with names, let me get this working first and then I could definitely use your help with improving the interface.

2021-09-26 16:58 UTC, junghans commented
Replaced by https://github.com/votca/votca/pull/766

2021-09-26 16:58 UTC, closed without merging